version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    hostname: grafana
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./data
        target: /var/lib/grafana
      - type: bind
        source: ./config/grafana.ini
        target: /etc/grafana/grafana.ini
      - type: bind
        source: ./dashboards
        target: /etc/grafana/provisioning/dashboards
      - type: bind
        source: ./datasources
        target: /etc/grafana/provisioning/datasources
    networks:
      - monitoring-network

networks:
  monitoring-network:
    driver: bridge